### PR TITLE
Add docker registry v2 support

### PR DESCRIPTION
**Pull request by flaccid**
Adds a location /v2/ stanza to the nginx configuration.

### CODE REVIEW

**Comment by aaw** [comment]
Thanks! I haven't tested this but it looks in line with the sample configs in docker/distribution's contrib directory. 

As is, I'm not sure how this patch changes the behavior of the existing proxy image. For example, can you run both distribution and docker-registry behind this proxy at the same time, like with [compose](https://github.com/docker/distribution/tree/master/contrib/compose), or just one or the other? Can you modify the README to include instructions on using it? Right now, the instructions are specific to using this as a proxy for docker-registry.

**Comment by flaccid** [comment]
@aaw before I do so can you let me know if the old docker-registry supported v2?

**Comment by fancyremarker** [comment]
Hi @flaccid, I'm going to close this one out since the old docker-registry did not in fact support v2. However, we're working on a new proxy that can work with both the old docker-registry and the new [docker/distribution](https://github.com/docker/distribution), so I'll refer back on this ticket once that's done.

**Comment by flaccid** [comment]
@fancyremarker https://github.com/aptible/docker-registry-proxy/pull/5 merged so I guess we're all good now :)

**Pull request closed without merging**
